; PlatformIO Project Configuration
; Target: ORION Interaction ESP32 (ESP32 DOIT DevKit V1)
; Manages touch sensors and TFT ILI9225 emotion display via micro-ROS serial.
; Docs: https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyESP32_2
board_microros_distro = jazzy
board_microros_transport = serial
lib_deps =
	https://github.com/micro-ROS/micro_ros_platformio
	nkawu/TFT 22 ILI9225@^1.4.5