#!/usr/bin/env python3
"""One-shot MPU6050 calibration tool for the ORION G Mov module.

Usage (robot still and level on a flat surface):
    ros2 run orion_utils_py mpu6050_calibration [--bus BUS] [--addr ADDR] [--samples N]

Collects accelerometer and gyroscope samples, computes per-axis biases, and
writes them to ~/.ros/mpu6050_calibration.yaml.  Restart mpu6050_node
afterwards so it loads the new offsets.

Bias convention
---------------
  accel: bias_x/y  = mean of horizontal axes (should be 0 when level)
         bias_z    = mean(az) - g  (removes gravity from the Z-axis mean)
  gyro:  bias_x/y/z = mean of each axis (should be 0 when still)

Correction applied by mpu6050_node:
  corrected = raw - bias
  => at rest: horizontal accel ≈ 0, vertical accel ≈ +g, gyro ≈ 0
"""

import argparse
import math
import os
import sys
import time

import smbus2

_REG_PWR_MGMT_1   = 0x6B
_REG_ACCEL_XOUT_H = 0x3B
_REG_GYRO_XOUT_H  = 0x43
_ACCEL_SCALE      = 16384.0    # LSB/g  (±2g range)
_GYRO_SCALE       = 131.0      # LSB/°/s (±250°/s range)
_G                = 9.80665    # m/s²
_SAMPLE_PERIOD    = 0.05       # seconds (20 Hz)
_PROGRESS_STEP    = 50         # print progress every N samples


def _read_raw(bus: smbus2.SMBus, addr: int, reg: int) -> int:
    """Read a signed 16-bit big-endian value from the given register."""
    data = bus.read_i2c_block_data(addr, reg, 2)
    raw  = (data[0] << 8) | data[1]
    return raw - 65536 if raw > 32767 else raw


def _collect(bus: smbus2.SMBus, addr: int, n: int):
    """Return per-axis sums for accel (m/s²) and gyro (rad/s) over n samples."""
    ax = ay = az = gx = gy = gz = 0.0
    for i in range(n):
        ax += _read_raw(bus, addr, _REG_ACCEL_XOUT_H)     * _G / _ACCEL_SCALE
        ay += _read_raw(bus, addr, _REG_ACCEL_XOUT_H + 2) * _G / _ACCEL_SCALE
        az += _read_raw(bus, addr, _REG_ACCEL_XOUT_H + 4) * _G / _ACCEL_SCALE
        gx += _read_raw(bus, addr, _REG_GYRO_XOUT_H)      * math.pi / (180.0 * _GYRO_SCALE)
        gy += _read_raw(bus, addr, _REG_GYRO_XOUT_H + 2)  * math.pi / (180.0 * _GYRO_SCALE)
        gz += _read_raw(bus, addr, _REG_GYRO_XOUT_H + 4)  * math.pi / (180.0 * _GYRO_SCALE)
        if (i + 1) % _PROGRESS_STEP == 0:
            print(f'  {i + 1}/{n}')
        time.sleep(_SAMPLE_PERIOD)
    return ax, ay, az, gx, gy, gz


def _save_yaml(path: str, biases: dict) -> None:
    """Write calibration biases to a YAML file without external dependencies."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write('# MPU6050 calibration — generated by mpu6050_calibration\n')
        f.write('accel_bias:\n')
        f.write(f"  x: {biases['accel_x']:.8f}\n")
        f.write(f"  y: {biases['accel_y']:.8f}\n")
        f.write(f"  z: {biases['accel_z']:.8f}\n")
        f.write('gyro_bias:\n')
        f.write(f"  x: {biases['gyro_x']:.8f}\n")
        f.write(f"  y: {biases['gyro_y']:.8f}\n")
        f.write(f"  z: {biases['gyro_z']:.8f}\n")


def main():
    parser = argparse.ArgumentParser(
        description='One-shot MPU6050 bias calibration for the ORION G Mov module.'
    )
    parser.add_argument('--bus',     type=int,
                        default=1,    help='I2C bus number (default: 1)')
    parser.add_argument('--addr',    type=lambda x: int(x, 0),
                        default=0x68, help='I2C address (default: 0x68)')
    parser.add_argument('--samples', type=int,
                        default=500,  help='Samples to collect (default: 500 ≈ 25 s)')
    parser.add_argument('--yes', action='store_true',
                        help='Skip the interactive prompt (for use from launch files)')
    args = parser.parse_args()

    duration = args.samples * _SAMPLE_PERIOD
    out_path = os.path.expanduser('~/.ros/mpu6050_calibration.yaml')

    print('MPU6050 Calibration Tool')
    print('════════════════════════')
    print(f'  I2C bus    : {args.bus}')
    print(f'  I2C addr   : {hex(args.addr)}')
    print(f'  Samples    : {args.samples}  (~{duration:.0f} s at 20 Hz)')
    print(f'  Output     : {out_path}')
    print()
    print('  ► Place the robot on a flat, level surface.')
    print('  ► Keep it completely still during collection.')
    print()

    if not args.yes:
        try:
            input('Press Enter to start, or Ctrl+C to abort...')
        except KeyboardInterrupt:
            print('\nAborted.')
            sys.exit(0)

    print()
    bus = smbus2.SMBus(args.bus)
    bus.write_byte_data(args.addr, _REG_PWR_MGMT_1, 0x00)  # wake up sensor
    time.sleep(0.1)                                          # settling time

    print(f'Collecting {args.samples} samples...')
    try:
        ax_s, ay_s, az_s, gx_s, gy_s, gz_s = _collect(bus, args.addr, args.samples)
    except Exception as exc:
        print(f'\nERROR reading sensor: {exc}')
        bus.close()
        sys.exit(1)
    finally:
        bus.close()

    n = args.samples
    biases = {
        'accel_x': ax_s / n,
        'accel_y': ay_s / n,
        'accel_z': az_s / n - _G,   # subtract gravity so node sees ~0 when still
        'gyro_x':  gx_s / n,
        'gyro_y':  gy_s / n,
        'gyro_z':  gz_s / n,
    }

    print()
    print('Bias results:')
    print(f"  accel  x={biases['accel_x']:+.6f}  y={biases['accel_y']:+.6f}"
          f"  z={biases['accel_z']:+.6f}  m/s²")
    print(f"  gyro   x={biases['gyro_x']:+.6f}  y={biases['gyro_y']:+.6f}"
          f"  z={biases['gyro_z']:+.6f}  rad/s")

    _save_yaml(out_path, biases)

    print()
    print(f'Calibration saved to: {out_path}')
    print('Restart mpu6050_node to apply the new offsets.')


if __name__ == '__main__':
    main()
